export type AucklandSuburb = {
  name: string;
  area: "Central" | "Northern" | "Eastern";
  boundarySubdivision: string;
};

export const AUCKLAND_SUBURBS: AucklandSuburb[] = [
  { name: "Auckland Central", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Arch Hill", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Avondale", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Balmoral", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Eden Terrace", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Epsom", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Freemans Bay", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Glen Innes", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Grafton", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Greenlane", area: "Central", boundarySubdivision: "Maungakiekie" },
  { name: "Grey Lynn", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Herne Bay", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Hillsborough", area: "Central", boundarySubdivision: "Maungakiekie" },
  { name: "Kingsland", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Kohimarama", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Meadowbank", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Mission Bay", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Morningside", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Mount Albert", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Mount Eden", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Mount Roskill", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Mount Wellington", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Newmarket", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Newton", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "One Tree Hill", area: "Central", boundarySubdivision: "Maungakiekie" },
  { name: "Onehunga", area: "Central", boundarySubdivision: "Maungakiekie" },
  { name: "Orakei", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Owairaka", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Panmure", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Parnell", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Point Chevalier", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Point England", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Ponsonby", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Remuera", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Royal Oak", area: "Central", boundarySubdivision: "Maungakiekie" },
  { name: "Saint Heliers", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Saint Johns", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Sandringham", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Stonefields", area: "Central", boundarySubdivision: "Tamaki" },
  { name: "Three Kings", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Waterview", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Western Springs", area: "Central", boundarySubdivision: "Owairaka" },
  { name: "Westmere", area: "Central", boundarySubdivision: "Maungawhau" },
  { name: "Albany", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Bayswater", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Beach Haven", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Belmont", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Birkenhead", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Browns Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Campbells Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Castor Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Devonport", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Forrest Hill", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Glenfield", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Greenhithe", area: "Northern", boundarySubdivision: "Kumeu" },
  { name: "Hauraki", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Hillcrest", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Long Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Mairangi Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Milford", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Murrays Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Northcote", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Northcross", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Oteha", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Pinehill", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Rothesay Bay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Rosedale", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Stanley Point", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Sunnynook", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Takapuna", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Torbay", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Unsworth Heights", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Wairau Valley", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Windsor Park", area: "Northern", boundarySubdivision: "East Coast Bays" },
  { name: "Burswood", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "Botany Downs", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "Bucklands Beach", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Cockle Bay", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Dannemora", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "East Tamaki", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "Eastern Beach", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Farm Cove", area: "Eastern", boundarySubdivision: "Pakuranga" },
  { name: "Flat Bush", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "Golflands", area: "Eastern", boundarySubdivision: "Pakuranga" },
  { name: "Half Moon Bay", area: "Eastern", boundarySubdivision: "Pakuranga" },
  { name: "Highland Park", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Howick", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Huntington Park", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "Mellons Bay", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Northpark", area: "Eastern", boundarySubdivision: "Botany" },
  { name: "Pakuranga", area: "Eastern", boundarySubdivision: "Pakuranga" },
  { name: "Pakuranga Heights", area: "Eastern", boundarySubdivision: "Pakuranga" },
  { name: "Shelly Park", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Somerville", area: "Eastern", boundarySubdivision: "Howick" },
  { name: "Sunnyhills", area: "Eastern", boundarySubdivision: "Pakuranga" },
  { name: "Wai O Taiki Bay", area: "Eastern", boundarySubdivision: "Tamaki" },
  { name: "Whitford", area: "Eastern", boundarySubdivision: "Botany" },
];
